kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/name: rabbitmq
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-net
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/enable-cors: 'false'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/preserve-trailing-slash: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rabbitmq.ryze.globalindustries.com
      secretName: tls-wld-ad
  rules:
    - host: rabbitmq.ryze.globalindustries.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ryze-amq
                port:
                  name: management
status:
  loadBalancer:
    ingress:
      - ip: 135.237.59.216
